"""sec

Revision ID: f7c5d2dc0e4e
Revises: e026245fbdfd
Create Date: 2022-02-27 14:26:44.975279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c5d2dc0e4e'
down_revision = 'e026245fbdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('con', sa.Column('now_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'con', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'con', type_='unique')
    op.drop_column('con', 'now_time')
    # ### end Alembic commands ###
